version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: manga-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # HTTP API 포트
      - "6334:6334"  # gRPC 포트 (선택사항)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    command: ["./qdrant", "--config-path", "/qdrant/config/production.yaml"]

volumes:
  qdrant_storage:
    driver: local 